feat: initialize store
gacky1601/niupi-backend pull request #35
Opened 2022-11-30 03:39 UTC by gacky1601

resolve #19

2022-11-30 03:46 UTC, justYu2001 commented
下次記得測試跟功能要分兩個 commit

請參考：
https://github.com/gacky1601/niupi-backend/wiki/開發規則#git-commit-訊息

2022-11-30 08:39 UTC, justYu2001 requested changes
1. `router.py` 第 1 行有沒有用到的 import，刪掉
2. `router.py` 第 15 行要改成 `store = service.get_store_by_user_id(db, user_id)`，不然會報錯

2022-12-01 03:16 UTC, justYu2001 commented
以後要 force push 前請先在群組問過，force push 是很危險的操作，不要隨意使用

2022-12-01 05:09 UTC, l1ang0226 approved these changes

2022-12-01 12:10 UTC, justYu2001 requested changes
store 的資料表定義要再加上 `CheckConstraint` 檢查以下幾點：
  - `name` 可以是 NULL 但不能是空字串
  - `cellphone_number` 和 `telephone_number` 的格式
  - `email` 要符合電子郵件格式
      - email 的正則表得式：`^[^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+$` 
 
參考資料：
- [SQLAlchemy 1.4 Documentation - CHECK Constraint](https://docs.sqlalchemy.org/en/14/index.html)
- [PostgreSQL - POSIX Regular Expressions](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP)
- [Use Regex in a 'CheckConstraint' from SQLAlchemy - Stack Overflow](https://stackoverflow.com/questions/44790668/use-regex-in-a-checkconstraint-from-sqlalchemy)

2022-12-01 13:13 UTC, gacky1601 commented on app/api/users/router.py
> +@router.get("", response_model=List[User])
我沒有第13行ㄟ。我ㄉrouter只有8行

2022-12-06 10:21 UTC, closed without merging