[Feat]: 更新使用者資料 API
gacky1601/niupi-backend pull request #45
Opened 2022-11-30 18:29 UTC by Zixun55

resolve #18

2022-12-01 03:13 UTC, justYu2001 requested changes

2022-12-01 03:13 UTC, justYu2001 commented on app/api/user/schemas.py
> +        cellphone_number_check = cellphone_number_Regex.search(value)
應該使用 `re.fullmatch`，或將正規表達是寫成 `^09\d{8}$`，因為我們要整段字串都符合規則，不是要找有沒有子字串符合規則

請參考：
- https://docs.python.org/3/library/re.html#re.fullmatch
- https://stackoverflow.com/questions/58774029/differences-between-re-match-re-search-re-fullmatch

2022-12-01 03:13 UTC, justYu2001 commented on app/api/user/schemas.py
> +
```suggestion
```

`re` 跟 `typing` 都是內建模組，中間不需要空行

2022-12-01 03:13 UTC, justYu2001 commented on app/api/user/schemas.py
>  from typing import Union
```suggestion
from typing import Union

```

2022-12-01 03:13 UTC, justYu2001 commented on app/api/user/service.py
>  from uuid import UUID
```suggestion
from uuid import UUID

```

2022-12-01 03:13 UTC, justYu2001 commented on app/api/user/service.py
>  from sqlalchemy.orm import Session
```suggestion
from sqlalchemy.orm import Session

```

2022-12-01 03:13 UTC, justYu2001 commented on app/api/user/service.py
> +    return db.query(User).filter(User.id == user_id).first()
```suggestion

    updated_user = get_user_by_id(db, user_id)

    return updated_user
```

2022-12-01 03:13 UTC, justYu2001 commented on app/api/user/schemas.py
> +    username: constr(min_length=1, strip_whitespace=True)
```suggestion
    email: Union[EmailStr, None]
    username: Union[constr(min_length=1, strip_whitespace=True), None]
```

`email` 和 `username` 也是 optional 的

2022-12-01 03:13 UTC, justYu2001 commented on tests/test_user.py
> +        "username": "update",
```suggestion
```

2022-12-01 03:13 UTC, justYu2001 commented on tests/test_user.py
> +        "username": "update",
```suggestion
```

2022-12-01 03:13 UTC, justYu2001 commented on tests/test_user.py
> +        "username": "update",
```suggestion
```

2022-12-01 03:13 UTC, justYu2001 commented on tests/test_user.py
> +        "username": "update",
```suggestion
```

2022-12-01 05:10 UTC, l1ang0226 approved these changes

2022-12-01 12:20 UTC, justYu2001 requested changes
user 的資料表定義要再加上 `CheckConstraint` 檢查以下幾點：
  - `cellphone_number`  的格式
  - `email` 要符合電子郵件格式
      - email 的正則表得式：`^[^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+$` 
 
參考資料：
- [SQLAlchemy 1.4 Documentation - CHECK Constraint](https://docs.sqlalchemy.org/en/14/index.html)
- [PostgreSQL - POSIX Regular Expressions](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP)
- [Use Regex in a 'CheckConstraint' from SQLAlchemy - Stack Overflow](https://stackoverflow.com/questions/44790668/use-regex-in-a-checkconstraint-from-sqlalchemy)

2022-12-01 12:20 UTC, justYu2001 commented on app/api/user/schemas.py
> +    cellphone_number: Union[constr(min_length=1, strip_whitespace=True), None]
```suggestion
    address: Optional[constr(min_length=1, strip_whitespace=True)]
    cellphone_number: Optional[constr(min_length=1, strip_whitespace=True)]
```

2022-12-05 02:29 UTC, justYu2001 requested changes

2022-12-05 02:29 UTC, justYu2001 commented on app/api/user/schemas.py
> +from typing import Union, Optional
```suggestion
from typing import Optional

```

2022-12-05 02:29 UTC, justYu2001 commented on app/api/user/schemas.py
> +from fastapi import HTTPException, status
```suggestion
from fastapi import HTTPException, status

```

2022-12-05 02:29 UTC, justYu2001 commented on app/api/user/schemas.py
> +        name='cellphone_numbercheck'))
```suggestion
```

`CheckConstraint` 是定義在資料庫的資料表的，要寫在 `model.py`

2022-12-05 02:29 UTC, justYu2001 commented on app/api/user/service.py
> +    db.query(User).filter(User.id == user_id).update(payload.dict(), synchronize_session="fetch")
```suggestion
    db.query(User) \
      .filter(User.id == user_id) \
      .update(payload.dict(exclude_none=True), synchronize_session="fetch")

```

如果不將 `payload.dice()` 的 `exclude_none` 傳 `True` 的話，請求沒指定值的屬性或被設成 `None`，造成沒有要改變的欄位被設成 `None`。所以要將  `payload.dice()` 的 `exclude_none` 傳 `True` 將值是 `None` 的屬性拿掉

2022-12-05 02:29 UTC, justYu2001 commented on app/api/user/service.py
> +    updated_user = get_user_by_id(db, user_id)
```suggestion

    updated_user = get_user_by_id(db, user_id)
```

2022-12-05 02:32 UTC, justYu2001 requested changes

2022-12-05 02:32 UTC, justYu2001 commented on app/api/user/schemas.py
> +from sqlalchemy import CheckConstraint
```suggestion
```

2022-12-05 02:43 UTC, justYu2001 requested changes

2022-12-05 02:43 UTC, justYu2001 commented on app/api/user/schemas.py
> +    ]
```suggestion
    cellphone_number: Optional[
        constr(
            min_length=1,
            strip_whitespace=True,
            regex=validator.cellphone_number_regex
        )
    ]
```

2022-12-06 02:28 UTC, justYu2001 requested changes

2022-12-06 02:28 UTC, justYu2001 commented on app/api/user/schemas.py
> +from typing import Optional
```suggestion
from typing import Optional

```

2022-12-06 02:28 UTC, justYu2001 commented on app/api/user/service.py
> +              synchronize_session="fetch")
```suggestion
      .update(payload.dict(exclude_none=True), synchronize_session="fetch")

```

2022-12-06 02:28 UTC, justYu2001 commented on app/api/user/models.py
> +    name='cellphone_numbercheck')
```suggestion
CheckConstraint(
    "REGEXP_LIKE(email,'^[a-zA-Z0-9]+@+[a-zA-Z0-9-]+.+([a-zA-Z]{2,4})$')",
    name='email_check'
)

CheckConstraint(
    "REGEXP_LIKE(cellphone_number,'^09+([0-9]{8})$')",
    name='cellphone_number_check'
)
```

2022-12-06 08:42 UTC, justYu2001 reviewed
在本機打 git merge main 之後再 push 一次

2022-12-06 08:49 UTC, justYu2001 approved these changes

2022-12-06 08:51 UTC, merged