修改登入成功的測試
gacky1601/niupi-backend pull request #46
Opened 2022-12-01 06:34 UTC by justYu2001

因為 #31 所以登入測試要重寫

2022-12-02 16:02 UTC, l1ang0226 approved these changes

2022-12-03 11:48 UTC, ntut-xuan commented on tests/conftest.py
> +from bcrypt import hashpw, gensalt
It should be `bcrypt < fastapi < sqlalchemy` since `b < f < s` in lexicographical order.

2022-12-03 15:14 UTC, gacky1601 approved these changes

2022-12-03 15:54 UTC, ntut-xuan commented on tests/conftest.py
>  from fastapi.testclient import TestClient
建議，可能存在或不存在於 PEP 8：

```python
import pytest # <--- 讓 import 在 from 的上方
from bcrypt import hashpw, gensalt # <--- 讓 from 在 import 的下方
from sqlalchemy.orm import Session
from fastapi.testclient import TestClient
```

2022-12-03 16:00 UTC, ntut-xuan commented on tests/conftest.py
>  from fastapi.testclient import TestClient
```python
from fastapi.testclient import TestClient # <--- f 的字典序小於 s，f 應該要在前面。
from sqlalchemy.orm import Session`
```

2022-12-05 07:35 UTC, ntut-xuan requested changes

2022-12-05 07:35 UTC, ntut-xuan commented on tests/conftest.py
> +from bcrypt import hashpw, gensalt
```python
from bcrypt import hashpw, gensalt # gensalt < hashpw.
```

2022-12-06 05:43 UTC, merged