初始化商店資料 API
gacky1601/niupi-backend pull request #51
Opened 2022-12-06 10:22 UTC by gacky1601

resolve #19

2022-12-06 13:24 UTC, justYu2001 requested changes

2022-12-06 13:24 UTC, justYu2001 commented on app/api/store/models.py
> +                index=True, default=uuid.uuid4)
```suggestion
    id = Column(UUID(as_uuid=True), primary_key=True, index=True, default=uuid.uuid4)
```

2022-12-06 13:24 UTC, justYu2001 commented on app/api/store/models.py
> +from app.utils.validator import cellphone_number_regex, telephone_number_regex, email_regex
```suggestion
from app.utils.validator import cellphone_number_regex,  email_regex, telephone_number_regex
```

2022-12-06 13:24 UTC, justYu2001 commented on app/api/store/models.py
> +from sqlalchemy import Column, String, ForeignKey, CheckConstraint
```suggestion
from sqlalchemy import  CheckConstraint, Column, String, ForeignKey
```

2022-12-06 13:24 UTC, justYu2001 commented on app/api/store/models.py
> +    "REGEXP_LIKE(Store.cellphone_number," + cellphone_number_regex,
```suggestion
    f"REGEXP_LIKE(Store.cellphone_number, {ellphone_number_regex})",
```

少了右邊的括號

2022-12-06 13:24 UTC, justYu2001 commented on app/api/store/models.py
> +    "REGEXP_LIKE(Store.telephone_number," + telephone_number_regex,
```suggestion
    f"REGEXP_LIKE(Store.telephone_number, {telephone_number_regex})",
```

同上

2022-12-06 17:22 UTC, l1ang0226 approved these changes

2022-12-07 06:53 UTC, justYu2001 requested changes

2022-12-07 10:56 UTC, justYu2001 reviewed
再處理合併衝突就可以 merge 了

2022-12-07 12:24 UTC, justYu2001 approved these changes

2022-12-07 12:24 UTC, merged