讀取商品圖片API
gacky1601/niupi-backend pull request #55
Opened 2022-12-08 10:48 UTC by l1ang0226

resolve #53

2022-12-08 11:43 UTC, justYu2001 requested changes

2022-12-08 11:43 UTC, justYu2001 commented on app/api/items/service.py
> +from .models import ItemPhoto
```suggestion
from sqlalchemy import func
from sqlalchemy.dialects.postgresql import ARRAY, UUID
from sqlalchemy.orm import Session
```

2022-12-08 11:43 UTC, justYu2001 commented on app/api/items/service.py
> +    return db.query(photos_agg).filter(item_id == ItemPhoto.item_id).first()
```suggestion
    return database.query(ItemPhoto).filter(ItemPhoto.item_id == item_id).all()
```

2022-12-08 11:43 UTC, justYu2001 commented on app/api/items/exceptions.py
> +)
```suggestion
```

沒有用到

2022-12-08 11:43 UTC, justYu2001 commented on app/api/items/router.py
> +@router.get("/{item_id}/photos", response_model=ItemPhoto)
```suggestion
@router.get("/{item_id}/photos", response_model=list[UUID])
```

2022-12-08 11:43 UTC, justYu2001 commented on app/api/items/router.py
> +    return photos_id
```suggestion
    photo_ids = get_photos_by_item_id(db, item.id)

    return photo_ids
```

是拿到多個「照片的 ID」，不是「多個照片」的 ID

2022-12-08 11:43 UTC, justYu2001 commented on app/api/items/service.py
> +def get_photo_by_item_id(db: Session, item_id: UUID4):
```suggestion
def get_photos_by_item_id(database: Session, item_id: UUID4):
```

2022-12-08 11:43 UTC, justYu2001 commented on app/api/items/service.py
>      return db.execute(statement).first()
```suggestion
    return database.execute(statement).first()
```

2022-12-08 11:43 UTC, justYu2001 commented on app/api/items/service.py
>  def get_item_by_item_id(db: Session, item_id: UUID4):
```suggestion
def get_item_by_item_id(database: Session, item_id: UUID4):
```

2022-12-08 11:43 UTC, justYu2001 commented on app/api/items/router.py
> +from .exceptions import PhotoNotFound
```suggestion
```

2022-12-08 11:43 UTC, justYu2001 commented on app/api/items/schemas.py
> +    photo_ids: list[UUID4]
```suggestion
```

直接回傳一個陣列就好，需求打錯了，抱歉。

2022-12-13 09:42 UTC, justYu2001 requested changes

2022-12-13 09:42 UTC, justYu2001 commented on app/api/items/router.py
> +from pydantic import UUID4
```suggestion
from pydantic import UUID4

```

2022-12-13 09:42 UTC, justYu2001 commented on app/api/items/service.py
>  from .models import Item
```suggestion

from .models import Item, ItemPhoto
```

2022-12-13 09:42 UTC, justYu2001 commented on app/api/items/service.py
> +    print(photo_ids)
改成自己寫 SQL，如果能盡量不用 Python 處理就不要用，效能會比較好

2022-12-13 13:04 UTC, l1ang0226 commented on app/api/items/service.py
> +    print(photo_ids)
我用效能比較好的方式了.jpg

2022-12-13 14:42 UTC, justYu2001 requested changes

2022-12-13 14:42 UTC, justYu2001 commented on app/api/items/service.py
> +    result = database.execute(statement).first()
```suggestion
    statement = (
        f"""
        SELECT id
        FROM item_photo
        WHERE item_photo.item_id='{item_id}'
        """
    )

    photos = database.execute(statement).all()
```

2022-12-13 14:42 UTC, justYu2001 commented on app/api/items/service.py
> +    return result[0]
```suggestion
    return photos
```

2022-12-14 05:27 UTC, justYu2001 approved these changes

2022-12-14 05:27 UTC, merged