刪除商品圖片api
gacky1601/niupi-backend pull request #70
Opened 2022-12-16 12:21 UTC by l1ang0226

resolve #59 

測試:
有測試刪除UUID不在商品圖片ID中的。
剩餘都於Issue的說明一樣

2022-12-18 01:59 UTC, justYu2001 requested changes

2022-12-18 01:59 UTC, justYu2001 commented on app/api/items/router.py
> +    print(photo_ids)
```suggestion
```

2022-12-18 01:59 UTC, justYu2001 commented on app/api/items/router.py
> +    return result
```suggestion
    photo_ids = service.delete_photos(db, item.id, photo_ids)
    return photo_ids
```

2022-12-18 01:59 UTC, justYu2001 commented on app/api/items/service.py
> +    return restPhotos
```suggestion
   photos = get_photos_by_item_id(db, Item_id)
   
   if photos is None:
       return []
       
    return photo_ids
```

不要複製貼上寫過的程式碼

2022-12-19 06:21 UTC, justYu2001 requested changes

2022-12-19 06:21 UTC, justYu2001 commented on app/api/items/service.py
> +    query.delete(synchronize_session=False)
```suggestion
    database.query(ItemPhoto).filter(ItemPhoto.id.in_(photos)).delete(synchronize_session=False)
```

2022-12-19 06:21 UTC, justYu2001 commented on app/api/items/service.py
> +        photos: conlist(UUID4, min_items=1)
確認一下縮排是不是四個空白鍵

2022-12-19 06:21 UTC, justYu2001 commented on app/api/items/router.py
> +        db: Session = Depends(get_db)
確認一下縮排是不是四個空白鍵

2022-12-19 07:33 UTC, justYu2001 requested changes

2022-12-19 07:33 UTC, justYu2001 commented on app/api/items/router.py
> +    photo_ids = service.delete_photos(db, item.id, photo_ids)
```suggestion
    payload: conlist(UUID4, min_items=1),
    item: Item = Depends(validate_item_id),
    db: Session = Depends(get_db)
):

    photo_ids = service.delete_photos(db, item.id, payload)
```

不要改到參數的值

2022-12-19 07:35 UTC, justYu2001 requested changes

2022-12-19 07:35 UTC, justYu2001 commented on app/api/items/service.py
> +    database.query(ItemPhoto).filter(ItemPhoto.id.in_(photos)).delete(synchronize_session=False)
```suggestion
    payload: conlist(UUID4, min_items=1)
):
    database.query(ItemPhoto).filter(ItemPhoto.id.in_(payload)).delete(synchronize_session=False)
```

2022-12-19 08:20 UTC, justYu2001 approved these changes

2022-12-19 08:25 UTC, gacky1601 approved these changes

2022-12-20 08:55 UTC, merged