新增商品圖片 API
gacky1601/niupi-backend pull request #71
Opened 2022-12-20 07:25 UTC by Zixun55

resolve #58

2022-12-20 08:53 UTC, justYu2001 requested changes

2022-12-20 08:53 UTC, justYu2001 commented on app/api/items/router.py
> +        db: Session = Depends(get_db)
確認縮排是不是 4 個空白見

2022-12-20 08:53 UTC, justYu2001 commented on app/api/items/schemas.py
> +from pydantic import BaseModel, UUID4, constr, conlist
```suggestion
from pydantic import BaseModel, UUID4, conlist, constr
```

2022-12-20 08:53 UTC, justYu2001 commented on app/api/items/service.py
> +        db.commit()
不要用 for 去重複執行 SQL 命令，效能會很差
去 Google 要怎麼只用 SQL 解決
關鍵字下 "sql batch insert" 應該可以找到解決方法

2022-12-20 08:53 UTC, justYu2001 commented on tests/test_photo_ids.py
> +    assert response.status_code == 200
```suggestion
    assert response.status_code == 201
```

新增成功回傳的狀態碼要是 201，需求打錯了，issue 那邊有更新了

2022-12-20 08:59 UTC, gacky1601 requested changes

2022-12-20 08:59 UTC, gacky1601 commented on app/api/items/schemas.py
> +from pydantic import BaseModel, UUID4, constr, conlist
```suggestion
from pydantic import BaseModel, UUID4, constr
```

2022-12-20 09:07 UTC, gacky1601 requested changes

2022-12-20 09:07 UTC, gacky1601 commented on app/api/items/service.py
> +    for i in range(len(photos)):
```suggestion
```

2022-12-21 02:50 UTC, justYu2001 requested changes

2022-12-21 02:50 UTC, justYu2001 commented on app/api/items/service.py
> +def add_photos(db: Session, item_id: UUID4, photos: conlist(UUID4, min_items=1)):
```suggestion
def add_photos(db: Session, item_id: UUID4, new_photo_ids: conlist(UUID4, min_items=1)):
```

不要動到函式的參數（後面的程式碼有將 photos 重新賦值）

2022-12-21 02:50 UTC, justYu2001 commented on app/api/items/service.py
> +    db.query(Item).filter(Item.id == item_id).first()
```suggestion
```

這行沒用到吧？

2022-12-21 02:50 UTC, justYu2001 commented on app/api/items/service.py
> +    db.bulk_save_objects(new_item_photo)
```suggestion
    new_item_photos = [ItemPhoto(id=photo_id, item_id=item_id) for photo_id in new_photo_ids]
    db.bulk_save_objects(new_item_photos)
```

2022-12-21 04:40 UTC, closed without merging