讀取商品 API
gacky1601/niupi-backend pull request #82
Opened 2022-12-23 16:48 UTC by linhowell

resolve #34

2022-12-23 20:44 UTC, Zixun55 commented on app/api/items/router.py
> +def creat_item(payload: ItemCreate, db: Session = Depends(get_db)):
```suggestion

@router.post("", response_model=Item, status_code=201)
def create_item(payload: ItemCreate, db: Session = Depends(get_db)):
```

2022-12-23 20:45 UTC, Zixun55 commented on app/api/items/router.py
> +    new_item = service.creat_new_item(db, payload)
```suggestion
    store = get_store_by_store_id(db, payload.store_id)
    
    if store is None:
        raise StoreNotFound
        
    new_item = service.creat_new_item(db, payload)
```

2022-12-23 20:46 UTC, Zixun55 commented on app/api/items/service.py
> +from .schemas import ItemUpdate, ItemCreate
```suggestion
from .schemas import ItemCreate, ItemUpdate
```

2022-12-23 20:47 UTC, Zixun55 commented on app/api/items/service.py
> +    new_item = get_item_by_item_id(db, item.id)
```suggestion
def creat_new_item(db: Session, payload: ItemCreate):
    item = Item(
        store_id=payload.store_id,
        name=payload.name,
        description=payload.description,
        price=payload.price,
        inventory=payload.inventory,
    )
    db.add(item)
    db.commit()
    
    new_item = get_item_by_item_id(db, item.id)
```

2022-12-23 20:48 UTC, Zixun55 commented on app/api/items/service.py
> +    new_item = get_item_by_item_id(db, item.id)
```suggestion
    db.commit()
    
    new_item = get_item_by_item_id(db, item.id)
```

2022-12-23 20:48 UTC, Zixun55 commented on app/api/items/service.py
> +    new_item = get_item_by_item_id(db, item.id)
```suggestion
        db.commit()
        
    new_item = get_item_by_item_id(db, item.id)
```

2022-12-23 20:49 UTC, Zixun55 commented on tests/test_item.py
> +    assert response.status_code == 201
```suggestion

    assert response.status_code == 201
    assert response.json() == {
        "store_id": "49b2b69a-512c-4492-a5ea-50633893f8cc",
        "name": "marker",
        "description": "so many water",
        "price": 500,
        "inventory": 50,
        "id": item_id,
        'photo_ids': [
            "56cef54e-78c1-4c4d-9f4f-44ebcad5bcfa",
            "da27353b-b024-4c1c-bf3a-91c48f0698f4"
        ]
    }
```

2022-12-23 20:50 UTC, Zixun55 commented on tests/test_item.py
> +    assert response.json() == {
```suggestion
    item_id = response.json()["id"]
    
    assert response.json() == {
```

2022-12-23 20:50 UTC, Zixun55 commented on tests/test_item.py
> +    assert response.json() == {
```suggestion
    item_id = response.json()["id"]
    
    assert response.json() == {
```

2022-12-23 20:51 UTC, Zixun55 commented on tests/test_item.py
> +    assert response.json() == {
```suggestion
    response = client.post("/api/items", json=json)
    
    assert response.json() == {
```

2022-12-25 02:22 UTC, justYu2001 requested changes

2022-12-25 02:22 UTC, justYu2001 commented on app/api/items/router.py
> +    new_item = service.create_new_item(db, payload)
```suggestion

    new_item = service.create_new_item(db, payload)
```

2022-12-25 02:22 UTC, justYu2001 commented on app/api/items/service.py
> +    new_item = get_item_by_item_id(db, item.id)
```suggestion

```

2022-12-25 02:22 UTC, justYu2001 commented on app/api/items/service.py
> +    if photos is not None:
```suggestion

    if photos:
```

2022-12-25 02:22 UTC, justYu2001 commented on app/api/items/service.py
> +        db.commit()
```suggestion
        new_item_photos = [ItemPhoto(id=photo, item_id=item.id) for photo in photos]
        db.bulk_save_objects(new_item_photos)
```

2022-12-25 02:22 UTC, justYu2001 commented on app/api/items/service.py
> +    )
```suggestion
    )
    
```

2022-12-25 02:22 UTC, justYu2001 commented on app/api/items/service.py
> +    photos = payload.photo_ids
```suggestion

    photos = payload.photo_ids
```

2022-12-27 03:30 UTC, justYu2001 approved these changes

2022-12-27 03:30 UTC, merged