讀取購物車資訊 API
gacky1601/niupi-backend pull request #87
Opened 2022-12-28 08:58 UTC by Zixun55

resolve #52

2022-12-28 15:17 UTC, l1ang0226 requested changes

2022-12-29 01:15 UTC, l1ang0226 requested changes

2022-12-29 01:15 UTC, l1ang0226 commented on app/api/carts/router.py
> +from .schemas import Cart
```suggestion

from . import service
from .dependencies import get_db
from .exceptions import UserNotFound
from .schemas import Cart
```

2022-12-29 01:15 UTC, l1ang0226 commented on app/api/carts/schemas.py
> +import datetime
```suggestion
import datetime

```

2022-12-29 01:45 UTC, l1ang0226 requested changes

2022-12-29 01:45 UTC, l1ang0226 commented on app/api/carts/router.py
> +def read_cart(user_id: UUID4, db: Session = Depends(get_db)):
```suggestion
@router.get("/{user_id}", response_model = Cart)
def read_cart(user_id: UUID4, db: Session = Depends(get_db)):
```

2022-12-29 02:53 UTC, Zixun55 commented on app/api/carts/router.py
> +def read_cart(user_id: UUID4, db: Session = Depends(get_db)):
這裡沒加response_model是有和彥宇討論過的

2022-12-29 03:50 UTC, l1ang0226 approved these changes

2022-12-29 03:50 UTC, l1ang0226 commented on app/api/carts/router.py
> +def read_cart(user_id: UUID4, db: Session = Depends(get_db)):
OK

2022-12-29 05:22 UTC, gacky1601 commented on app/api/carts/router.py
> +def read_cart(user_id: UUID4, db: Session = Depends(get_db)):
這裡好熱鬧喔

2022-12-29 05:47 UTC, closed without merging